name: CI Check

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Success Test
        run: echo "Workflow is running successfully! 🚀"
